<a href="https://colab.research.google.com/github/vennela28/AppliedAI/blob/master/LIVE_Pandas_and_NumPy_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas & NumPy -II

- For Pandas: https://www.machinelearningplus.com/python/101-pandas-exercises-python/
- For NumPy: https://www.machinelearningplus.com/python/101-numpy-exercises-python/
- L1, L2 and L3:
- Readability over Pythonic code if no hit to time and space complexity, especially when they are important.
- We will see many more examples in the next Code-Walkthrough sessions when we use Pandas in other chapters.

Pre-requisites: Sessions in Python programming + Course videos




## Pandas Problems

### Difficulty Level: L1

#### Combine ser1 and ser2 to form a dataframe.

In [ ]:

import numpy as np
import pandas as pd
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
print(ser1)
print(ser2)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64


In [ ]:
# Solution 1
df = pd.concat([ser1, ser2], axis=1) #https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html
print(df)
print("***********************************************************")

print(pd.concat([ser1, ser2]))


    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25
***********************************************************
0      a
1      b
2      c
3      e
4      d
5      f
6      g
7      h
8      i
9      j
10     k
11     l
12     m
13     n
14     o
15     p
16     q
17     r
18     s
19     t
20     u
21     v
22     w
23     x
24     y
25     z
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: object


In [ ]:
# Solution 2
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df)

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25


### Difficulty Level: L2

####  From ser1 remove items present in ser2.

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
# Google search: "pandas series set difference" ----> https://medium.com/@rodwan.bakkar/pandas-set-difference-fde7f4381b53

print(ser1.isin(ser2)) # https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html


0    False
1    False
2    False
3     True
4     True
dtype: bool


In [ ]:
print( ser1[ ~ ser1.isin(ser2) ] )

0    1
1    2
2    3
dtype: int64


### Diffculty Level: L3
#### Extract the valid emails from the series emails. The regex pattern for valid emails is provided as reference.



In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [ ]:
# Google "Pandas regex" ---> https://kanoki.org/2019/11/12/how-to-use-regex-in-pandas/

import re
print(emails.str.findall(pattern, flags=re.IGNORECASE))

print(type(emails.str))

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object
<class 'pandas.core.strings.StringMethods'>


### Difficiulty Level: L3

#### Get the positions of peaks (values surrounded by smaller values on both sides) in ser.

- We can apply the same logic we used earlier on NumPy arrays and lists earlier using loops
- I perfer easy to read code if the time-complexity doesnot change much.
- We will also a see pythonic code


In [ ]:
## PYTHONIC CODE

# https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.diff.html
# array-like: series also works
ser = pd.Series([2, 10, 5, 4, 9, 10, 2, 7, 3])

print(np.diff(ser))

[ 8 -5 -1  5  1 -8  5 -4]


In [ ]:
np.sign(np.diff(ser))

array([ 1, -1, -1,  1,  1, -1,  1, -1])

In [ ]:
dd = np.diff(np.sign(np.diff(ser)))
print(dd)

[-2  0  2  0 -2  2 -2]


In [ ]:
#print(np.where(dd == -2))
peak_locs = np.where(dd == -2)[0] + 1
print(peak_locs)

[1 5 7]


In [ ]:
# Alternative solution using Scipy
from scipy.signal import find_peaks
peaks, _ = find_peaks(ser)
print(peaks)

[1 5 7]


In [ ]:
# NON-PYTHONIC CODE
def findPeaks(s):
  r = []; # resultant peak indices
  
  if s[0] > s[1]: # boundary case
    r.append(0)
  
  for i in range(1,s.size-1): # GOOGLE: "length of a series"
    if (s[i] > s[i-1]) and (s[i] > s[i+1]):
      r.append(i)

  if s[s.size-1] > s[s.size-2]: # boundary case
    r.append(s.size-1)

  return r

findPeaks(ser)

[1, 5, 7]

In [ ]:
# PYTHONIC FUNCTIOn
def findPeaksPythonic(ser):
  #NOTE: Numpy Operations are inplementated in C and hence will be much faster.
  dd = np.diff(np.sign(np.diff(ser))) # additional space O(n)
  peak_locs = np.where(dd == -2)[0] + 1 
  return peak_locs

findPeaksPythonic(ser)


array([1, 5, 7])

In [ ]:

# Measure time taken to run

sRand  = pd.Series(np.random.randint(0,100, size=500))
print(sRand)

import time
start_time = time.time()

for i in range(1000):
  findPeaks(sRand)

end_time = time.time()
print("--- %s seconds ---" % (end_time - start_time))

0      98
1      27
2      24
3      34
4      80
       ..
495    28
496    32
497    30
498    64
499    64
Length: 500, dtype: int64
--- 18.57629704475403 seconds ---


In [ ]:
import time
start_time = time.time()

for i in range(1000):
  findPeaksPythonic(sRand)

end_time = time.time()
print("--- %s seconds ---" % (end_time - start_time))

--- 0.026500463485717773 seconds ---


In [ ]:
import time
start_time = time.time()

for i in range(1000):
  find_peaks(sRand)

end_time = time.time()
print("--- %s seconds ---" % (end_time - start_time))

--- 0.03279685974121094 seconds ---


- Speed of Pythonic code >> Speed of non-pythonic code [in this case due to NumPy arrays being heavily optimized]
- Space complexity of Pythonic > Space complexity of simple code
- Tradeoffs: Time, Space and Readability


### Difficulty Level: L2

- From a series, keep the top 2 most frequent 
items as it is and replace everything else as ‘Other’.

In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 10, [20]))
print(ser)

0     3
1     7
2     7
3     9
4     3
5     5
6     2
7     6
8     4
9     4
10    7
11    8
12    3
13    1
14    2
15    4
16    4
17    3
18    5
19    8
dtype: int64


In [ ]:
print(ser.value_counts())
print(type(ser.value_counts()))

4    4
3    4
7    3
8    2
5    2
2    2
9    1
6    1
1    1
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
print(ser.value_counts().index) 
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.index.html

Int64Index([4, 3, 7, 8, 5, 2, 9, 6, 1], dtype='int64')


In [ ]:
print(ser.value_counts().index[:2])

Int64Index([4, 3], dtype='int64')


In [ ]:
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
print(ser)

0         3
1     Other
2     Other
3     Other
4         3
5     Other
6     Other
7     Other
8         4
9         4
10    Other
11    Other
12        3
13    Other
14    Other
15        4
16        4
17        3
18    Other
19    Other
dtype: object


## NumPy Problems


### Difficulty Level: L2

#### Replace all odd numbers in arr with -1 without changing arr

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
out = np.where(arr % 2 == 1, -1, arr) #https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


### Difficulty Level : L3
#### Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
print(condition)
print(type(condition))

[False False False False False False False False False False False  True
 False False False False False False False False False False False False
  True False False False False  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]
<class 'numpy.ndarray'>


In [ ]:
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

### Difficulty Level: L3
#### Select the rows of iris_2d that does not have any nan value.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
# make values in random columns and rows = NAN
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [nan 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [nan 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 nan]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [nan 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 nan]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 nan]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 nan 0.6]
 [nan 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [nan 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:

print(~np.any(np.isnan(row)) for row in iris_2d)

<generator object <genexpr> at 0x7f28fee525c8>


In [ ]:
op = np.array([~np.any(np.isnan(row)) for row in iris_2d])

print(iris_2d[op])

[[5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.

### Difficulty Level: L2

#### Sort the iris dataset based on sepallength column.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [ ]:
print(iris)
print("*****************************************************")
print(iris[:,0].argsort()) #https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

In [ ]:
print(iris[iris[:,0].argsort()])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.

### Difficulty Level: L3

#### Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

In [ ]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)

#Output: [False  True False  True False False  True  True  True  True]

[0 0 3 0 2 4 2 2 2 2]


In [ ]:
# Create an all True array
out = np.full(a.shape[0], True) # all True
print(out)

# Find the index positions of unique elements
print(np.unique(a, return_index=True))
print(type(np.unique(a, return_index=True)))

unique_positions = np.unique(a, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False

print(out)

[ True  True  True  True  True  True  True  True  True  True]
(array([0, 2, 3, 4]), array([0, 4, 2, 5]))
<class 'tuple'>
[False  True False  True False False  True  True  True  True]


### Takeaways
#### 1. Break a problem into its sub components
#### 2. Try to write pythonic code if you can for each sub-component

#### 3. Else, use loops and other control flow statements. 
