In [1]:
import numpy as np

# Elementwise Operations

<h3> 1. Basic Operations </h3>

<h4> with scalars </h4>

In [15]:
a = np.array([1, 2, 3, 4]) # creates an array

a + 1

array([2, 3, 4, 5])

In [16]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

<h4> All arithmetic operates elementwise </h4>

In [17]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [18]:
a

array([1, 2, 3, 4])

In [21]:
a - b

array([-1.,  0.,  1.,  2.])

In [22]:
a * b

array([2., 4., 6., 8.])

In [26]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

print(c * c)

print('~~~~~~~~~~~~~~~~~~')

print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
~~~~~~~~~~~~~~~~~~
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


<h4> Comparisons </h4>

In [29]:
# element-wise comparisons

a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [30]:
a > b

array([False, False,  True, False])

In [32]:
# array-wise comparisons

a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

print(np.array_equal(a, b))
print(np.array_equal(a, c))

False
True


<h4> Logical Operations </h4>

In [33]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [34]:
np.logical_and(a, b)

array([ True, False, False, False])

<h4> Transcendental functions </h4>

In [36]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [38]:
np.log(a)

C:\Users\venne\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [39]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

<h4> Shape Mismatch </h4>

In [40]:
a = np.arange(4)

a + np.array([1, 4])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

<h3> Basic Reductions </h3>

<h4> computing sums </h4>

In [41]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [44]:
# sum by rows and columns

x = np.array([[1, 1], [3, 3]])
x

array([[1, 1],
       [3, 3]])

In [48]:
x.sum(axis = 0)   # columns - first dimension

array([4, 4])

In [50]:
x.sum(axis = 1)   # rows

array([2, 6])

<h4> Other reductions </h4>

In [51]:
x = np.array([1, 2, 3])
x.min()

1

In [52]:
x.max()

3

In [53]:
x.argmin()   # return the index of the minimum element

0

In [54]:
x.argmax()   # return the index of the maximum element

2

<h4> Logical Operations </h4>

In [59]:
np.all([True, True, False])   # Logical AND

False

In [60]:
np.any([True, False, False])   # Logical OR

True

In [57]:
# can be used for array comparisons
a = np.zeros((50, 50))
np.any(a!=0)

False

In [58]:
np.all(a == a)

True

In [61]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

<h4> Statistics </h4>

In [62]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [63]:
np.median(x)

1.5

In [64]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [65]:
x.std()   # full population standard deviation

0.82915619758885

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

In [68]:
# load data into numpy array object
data = np.loadtxt('populations.txt')

In [69]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [70]:
year, hares, lynxes, carrots = data.T   # columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [72]:
# The mean population over time
populations = data[:, 1:]  # : - take all the rows, 1: - take from 1st column
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [73]:
# sample standard deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [75]:
# which species has the highest population each year?
np.argmax(populations, axis = 1)   # axis = 1 - operate row-wise

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

<h3>Broadcasting </h3>

In [88]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)
print("~~~~~~~~~~~~~~")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
~~~~~~~~~~~~~~
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [89]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [90]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [91]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [92]:
a = a[:, np.newaxis] # adds a new axis -> 2D array - converting 1-D array to 2-D array
a.shape

(4, 1)

In [93]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [94]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

<h3> Array Shape Manipulation </h3>

<h4> Flattening </h4>

In [95]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()  # Returns a contiguous flattened array. 

array([1, 2, 3, 4, 5, 6])

In [96]:
a.T  # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

<h4> Reshaping </h4>

The inverse operation to flattening.

In [98]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [99]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [100]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

<h4> reshape may also return a copy! </h4>

In [106]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
print(a)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[50.  0.  0.  0.  0.  0.]


<h4> Adding a Dimension </h4>

In [107]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [108]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

<h4> Dimension Shuffling </h4>

In [112]:
a = np.arange(4*3*2).reshape(4, 3, 2)   # 4 matrices of 3 rows and 2 columns
a.shape

(4, 3, 2)

In [113]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [114]:
a[0, 2, 1]

5

<h4> Resizing </h4>

In [115]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [116]:
b = a
a.resize(4,)

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

<h4> Sorting Data </h4>

In [117]:
# sorting along an axis
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [118]:
# in-place sort
a.sort(axis = 1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [119]:
# sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [120]:
a[j]

array([1, 2, 3, 4])